### ISSUE TITLE
Issue with pileupCaller

### ISSUE THREAD

**Issue by mnievesc** [stschiff/sequenceTools#1]
Hi! I have installed the sequenceTools suite using haskell but when I try to run the pileupCaller I get the following error: hPutStr: illegal operation (handle is closed). Do you have any insight on what may be causing this error? I am using a MacOSx operating systemand haskell was installed using homebrew. Full command used was as follows:

samtools mpileup -R -B -q30 -Q20 -l pileup_files/pos_list.txt -f ~/Data_analyses/Ref-seqs/hg19-25chr-rCRS.mod.fa BAMfiles/PI_51.all.merged.uniq.rmdup.rescaled.bam | 
pileupCaller --sampleNames PI_51 --samplePopName PR -f ref.snp -o EigenStrat -e PI_51.ref > PI_51.ref.geno

Any help would be much appreciated!

Also sorry I accidentally pasted this in the wiki page earlier! But I erased it now.

Thank you,

Maria

**Comment by stschiff** [comment]
Hi Maria,

the error means that pileupCaller is trying to write to a file which doesn’t anymore exist at the time it tries to write. I can’t reproduce the issue. Which version of pileupCaller are you using? You can find out by running `pileupCaller —version`.

Have you checked that the `samtools mpileup` command produces a valid pileup output? Just pipe the mpileup output to `head` or `less` or so and check that things are correctly output. Then, when running pileupCaller, note the list of SNPs must of course be the same list of SNPs that you’ve asked mpileup to run on. So in your command, the files "pileup_files/pos_list.txt” and “ref.snp” must have the same positions.

Note also that the most recent version (1.2.1) changed the behaviour of the Eigenstrat output. Now, the three Eigenstrat files will be written all to files given the prefix as set with the `-e` option. The geno file is not anymore output to stdout. I’ve just updated the documentation to reflect that.

Stephan

**Comment by mnievesc** [comment]
Hi Stephan,

Thank you so much for responding! The version I was using was 1.2.0, after updating it using git pull the problem was resolved! 

Thanks again,

Maria

**Comment by stschiff** [comment]
OK, glad to hear!
