### ISSUE TITLE
Criticism and suggestion

### ISSUE THREAD

**Issue by zohalnew** [stschiff/sequenceTools#16]
If the authors had compiled these commands graphically for Windows
Or they put video tutorials
They did not have to waste their time answering problems
And it is unfortunate that in 2020 we work with the command line

**Comment by teepean** [comment]
You can download stack for Windows and compile sequenceTools yourself using the instructions from the first page.

https://docs.haskellstack.org/en/stable/install_and_upgrade/

stack install sequenceTools --resolver nightly

**Comment by stschiff** [comment]
Thanks. I consider this being resolved.
