### ISSUE TITLE
SeqFormatException "Error while parsing:Failed reading

### ISSUE THREAD

**Issue by idiltac** [stschiff/sequenceTools#20]
Hi, I (sadly) got this error, and I guess i have proper chromosome names

pileupCaller: SeqFormatException "Error while parsing: Failed reading: takeWhile1. Error occurred when trying to parse this chunk: "1 164142962 0.000000 rs16825782 A G\n1 30540958 0.000000 rs117896736 A
G\n1 4269798 0.000000 rs60017975 A G\n1 208829543 0.000000 rs60399096 A G\n1 14478216 0.000000 rs61777764 A G\n1 105670746 0.000000 rs574520203 A G\n1 164093437 0.000000 rs4481829 A T\n1 238993155
0.000000 rs74151442 C A\n1 105415429 0.000000 rs4130570 C A\n1 208962155 0.000000 rs112253445 C A\n1 106455333 0.000000 rs11184713 C A\n1 208947187 0.000000 rs12567605 C G\n1 164113052 0.000000 rs465
7345 C T\n1 14274833 0.000000 rs4661454 C T\n1 208948424 0.000000 rs7526845 C T\n1 105698821 0.000000 rs10881266 C T\n1 164094034 0.000000 rs12029341 C T\n1 194559737 0.000000 rs12038368 C T\n1 2387
95721 0.000000 rs12085041 C T\n1 105717897 0.000000 rs114869249 C T\n1 4094068 0.000000 rs12137595 C T\n1 164093272 0.000000 rs12760080 C T\n1 14487708 0.000000 rs1416633 G A\n1 105702806 0.000000 rs
72685540 G A\n1 14494500 0.000000 rs7529180 G A\n1 105698629 0.000000 rs7539065 G A\n1 239007234 0.000000 rs112548772 G A\n1 164159147 0.000000 rs10917942 G A\n1 164087927 0.000000 rs12044081 G A\n1...

I changed my snp file with this error message

pileupCaller: WrongInputOrderException "ordering violated: EigenstratSnpEntry {snpChrom = "1", snpPos = 164142962, snpGeneticPos = 0.0, snpId = "1_164142962", snpRef = 'A', snpAlt = 'G'} should come after EigenstratSnpEntry {snpChrom = "1", snpPos = 30540958, snpGeneticPos = 0.0, snpId = "1_30540958", snpRef = 'A', snpAlt = 'G'}"

And my final snp file is look like this

1 164142962 0.000000 rs16825782 A G
1 30540958 0.000000 rs117896736 A G
1 4269798 0.000000 rs60017975 A G
1 208829543 0.000000 rs60399096 A G
1 14478216 0.000000 rs61777764 A G
1 105670746 0.000000 rs574520203 A G
1 164093437 0.000000 rs4481829 A T
1 238993155 0.000000 rs74151442 C A
1 105415429 0.000000 rs4130570 C A
1 208962155 0.000000 rs112253445 C A

I don't have info about 3th column so I set it zero

**Comment by stschiff** [comment]
Well, as the error message indicates, you have an unordered SNP file, which is illegal. You can see that the SNP position aren't in order:

```
1 164142962 0.000000 rs16825782 A G
1 30540958 0.000000 rs117896736 A G
1 4269798 0.000000 rs60017975 A G
1 208829543 0.000000 rs60399096 A G
1 14478216 0.000000 rs61777764 A G
1 105670746 0.000000 rs574520203 A G
1 164093437 0.000000 rs4481829 A T
1 238993155 0.000000 rs74151442 C A
1 105415429 0.000000 rs4130570 C A
1 208962155 0.000000 rs112253445 C A
```

they are all over the place...
