### ISSUE TITLE
pileupCaller only outputing missing data in genofile

### ISSUE THREAD

**Issue by mscbig** [stschiff/sequenceTools#26]
Despite having checked carefully the format of my input files, all sites appear as missing data. 
Here is an example I grepped for one variable site.
In file positions 
1	131606

```samtools mpileup -R -B -l positions -f ref.fa sample_A.bam > pileup.txt```
In file pileup.txt 
1	131606	T	2	..	JJ

In file eigenpos
rs3983	1	0	131606	G	T

```pileupCaller --sampleNames A -f eigenpos -o EigenStrat -e sampleA.out < pileup.txt```

In file samplesA.out.geno.txt
9
In file samplesA.out.snp.txt
1_131606	1	0	131606	G	T

When outputing in Freqsum format, consistently produce missing data too
#CHROM	POS	REF	ALT	A(1)
1	131606	G	T	-1

Did I miss something obvious in formatting that causes this behaviour?

Thanks

**Comment by stschiff** [comment]
You've closed this, so can I assume you've solved the issue yourself?

**Comment by mscbig** [comment]
Yes sorry. I installed the latest version on my personal computer and thanks to the error message it generated I realized it's a problem of chromosome names that causes an error as the pileup file seems unordered.

**Comment by stschiff** [comment]
Ah OK. Good luck then :-)
