### ISSUE TITLE
Release for 1.5.3.1

### ISSUE THREAD

**Issue by jowodo** [stschiff/sequenceTools#33]
Hi, 

is it planed to do a release for the according tag 1.5.3.1? If so, when? 
I'm part of the administration team on a HPC system. To provide users with the newest software we check for github tags and in this case download from release. 

Thanks!

**Comment by stschiff** [comment]
Good point. Happy to make a release. Will leave this issue open until it's done.

**Comment by jowodo** [comment]
Amazing! Thanks a lot!

**Comment by stschiff** [comment]
OK, the release is out, and automatic GitHub actions are creating the executables now. But note that v1.5.3.1 is really of no user difference to v1.5.3. So you do not have to upgrade this time. I'll keep the issue open until the release is fully done.

**Comment by stschiff** [comment]
Done
