### ISSUE TITLE
Rs values missing from pileupCaller output

### ISSUE THREAD

**Issue by teepean** [stschiff/sequenceTools#4]
Hello!

I was wondering if there is a way to keep the rs values when creating Eigenstrat files with pileupCaller? At the moment the output looks like this. I am using HumanOriginsPublic2068.snp as the Eigenstrat positions file. 

> 1_752566	1	0	752566	G	A
> 1_842013	1	0	842013	T	G
> 1_891021	1	0	891021	G	A
> 1_903426	1	0	903426	C	T
> 1_949654	1	0	949654	A	G
> 1_1018704	1	0	1018704	A	G
> 1_1045331	1	0	1045331	G	A
> 1_1048955	1	0	1048955	A	G
> 1_1061166	1	0	1061166	T	C
> 1_1108637	1	0	1108637	G	A
> 1_1120431	1	0	1120431	G	A
> 1_1156131	1	0	1156131	T	C
> 1_1157547	1	0	1157547	T	C
> 1_1158277	1	0	1158277	G	A
> 1_1161780	1	0	1161780	C	T
> 1_1170587	1	0	1170587	C	T
> 1_1205155	1	0	1205155	A	C

**Comment by stschiff** [comment]
Yes, that was a choice that makes sense in our internal processing pipeline, but indeed isn’t a good default. I will change that and will let you know when it’s done.

Stephan

**Comment by teepean** [comment]
> Yes, that was a choice that makes sense in our internal processing pipeline, but indeed isn’t a good default. I will change that and will let you know when it’s done. Stephan

Thank you!

**Comment by teepean** [comment]
Looks like this was fixed recently.

**Comment by stschiff** [comment]
Yes, sorry. Indeed, never clarified this was fixed indeed.
