### ISSUE TITLE
Does pileupCaller output reference bases? 

### ISSUE THREAD

**Issue by Arkkienkeli** [stschiff/sequenceTools#5]
Hello, does it output all alleles like GATK3 GenotypeGVCF --includeAllSites ?

**Comment by Arkkienkeli** [comment]
@stschiff Could you please assist me on this? Thank you!

**Comment by stschiff** [comment]
Yes, it does if you don't give it a SNP list file.

**Comment by Arkkienkeli** [comment]
@stschiff 
Hi Stephan, thank you for the response. Still, I get all 0 in geno file (EigenStrat output).
From eigenstrat site:  0 means zero copies of reference allele.
I don't get any 1 or 2 in geno file. 

`pileupCaller --sampleNames fileq20Q20 --minDepth 1  -o EigenStrat -e filecall20Q20 < s-fileq20Q20.txt`

I tried  --minDepth 2 also, and I also tried decreasing to q10\Q10 in samtools mpileup. In this case, it produces more SNPs in output, but still all 0 in geno file.

**Comment by stschiff** [comment]
Not quite sure I follow this. Have you checked the pileup-output itself, before piping into pileupCaller? Have you checked that your samtools command works as expected, outputting all sites, with the correct reference and alternative alleles, and the expected pileup information?
