### ISSUE TITLE
Add bioconda recipe for sequenceTools

### ISSUE THREAD

**Issue by sc13-bioinf** [stschiff/sequenceTools#7]
The bionconda recipe for sequenceTools will give another way for people to install it easily. It will also make it easy to incorporate into eager2. The only way to get sequenceTools running in a bioconda recipe is by installing a pre-compiled static binary. To make this process easier, Travis CI can be used to build and publish this static binary automatically. Therefore there are the following things to do:

1. Create github account to be used by Travis CI
 - This will have write permission to your repos, hence the separate account to allow fine grained access control
2. Sign up for Travis CI:
 - https://docs.travis-ci.com/
3. Add a file to tell travis what to do:
 - https://github.com/gitter-bioinf/sequenceTools/blob/static-artifact-sc13/.travis.yml
4. Update bioconda recipe to install the new artifact:
 - https://github.com/sc13-bioinf/bioconda-recipes/tree/sequencetools

**Comment by stschiff** [comment]
Is this really the only way to get this into conda? Via precompiled binaries? Is there no way I can make a `stack install` pipeline within bioconda or something? @maxibor, can you confirm this as well?

**Comment by maxibor** [comment]
Creating a conda package needs two things:
- A `meta.yaml` file for recipe metadata
- A `build.sh` that contains the compilation instructions, which will be compiled by bioconda.

- Here are the official Bioconda instructions for building a conda package for Haskell: [bioconda.github.io/contributor/guidelines.html#haskell](https://bioconda.github.io/contributor/guidelines.html#haskell)
- Here is a bioconda recipe of a Haskell package [github.com/bioconda/bioconda-recipes/tree/master/recipes/ngless](https://github.com/bioconda/bioconda-recipes/tree/master/recipes/ngless)

**Comment by stschiff** [comment]
Thanks a lot. I'll have a look and see whether I can get that organised.

**Comment by sc13-bioinf** [comment]
So the reason why it is so hard is because conda recipes target centos6. It turns out that haskell is  too modern to build on this os. The only way to do would be to build an entire modern os from scratch in your recipe so you can then build haskell. Static binaries are therefore the only way to go until conda moves to something more recent.

**Comment by stschiff** [comment]
OK, I've decided to unassign myself from this and not pursue it further myself. It has low priority for me. There exists a simple and cross-platform way to install this, and making it even more convenient with conda is nice to have but not necessary. If someone wants to take this on, let me know, I'm happy to grant temporary write access to this repo if need be.
